spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutuongHCM
    username: postgres
    password: 4869
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
